name: Node.js CI Lint

on:
  push:
    branches: [ master, dev ]

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} to build

      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup Node.js
      run: npm i

    - name: Building package
      run: npm run build --if-present

    - name: Running lint
      run: npm run lint
      env:
        CI: true
